export const words={
    "commingSoonTitle":"به زودی با محصولات جذاب می‌آییم",
    "commingSoonDescription":"به کانال ایتای ما بپیوندید تا اولین کد تخفیف را دریافت کنید:",
    "login":"ورود | ثبت نام",
    "signOut":"خروج",
    "analytics":"آنالیز",
    "create":"ایجاد",
    "products":"محصولات",
    "orders":"سفارشات",
    "settings":"تنظیمات",
    "settingsTitle":"تنظیمات پروفایل",
    "settingsDescription":"پروفایتان را آپدیت کنید",
    "name":"نام",
    "namePlaceholder":"انتخاب نام (ترجیحا فارسی)",
    "nameDescription":"این نام کاربری شماست",
    "myOrders":"سفارشات من",
    "darkMode":"حالت شب",
    "lightMode":"حالت روز",
    "addProductTitle":"ایجاد محصول",
    "addProductSubTitle":"یک محصول جدید ایجاد کنید",
    "addProductTitleLabel":"عنوان محصول",
    "addProductTitleLabelPlaceholder":"مثلا خط کش شب یلدا",
    "addProductDescriptionLabel":"توضیحات",
    "addProductDescriptionLabelPlaceholder":"توضیحات بیشتری در مورد محصول",
    "addProductPriceLabel":"قیمت محصول",
    "addProductPriceLabelPlaceholder":"قیمت محصول بر حسب ریال",
    "addProductSubmitLabel":"ایجاد محصول",
    "editProductTitle":"ویرایش محصول",
    "editProductSubTitle":"محصول مورد نظر را ویرایش کنید",
    "editProductSubmitLabel":"ذخیره تغیرات",
    "IRR":"ریال",
    "eitaaCta":"کانال ایتای نوژاشاپ",
    "homeSeoTitle":"نوژاشاپ",
    "homeSeoDescription":"فروشگاه لوازم التحریز نوژاشاپ"

}